### ISSUE TITLE
No files shown and "Cannot find module 'mkdirp'" errror 

### ISSUE THREAD

**Issue by jan-schulz-k24** [tinytacoteam/zazu-file-finder#26]
I installed zazu (`{"version":"0.3.2","level":"debug","message":"app is ready"}`) on an ubuntu 16.10 64bit system and started it, but no files are found. When I open the app on the commandline (`/opt/zazu/zazu`), I get these errors:

```
λ /opt/zazu/zazu
module.js:457
    throw err;
    ^

Error: Cannot find module 'mkdirp'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/js/.zazu/plugins/tinytacoteam/zazu-file-finder/lib/appInfo.js:6:16)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
[more mkdirp errors every x seconds]
```

**Comment by blainesch** [comment]
Do you mind pasting the rest of the log file in a gist?

**Comment by jan-schulz-k24** [comment]
https://gist.github.com/jan-schulz-k24/32023dedf056bd2cb0fd6c380c2e66dd

**Comment by blainesch** [comment]
@jan-schulz-k24 the plugins don't appear to have been installed with that log file. The log files are split by day, not when zazu is opened. Is it possible to find an earlier log file? You'd see something like `npm install` in one of them.

Is it possible you installed them with an earlier version of zazu?

**Comment by twang2218** [comment]
@jan-schulz-k24 This could be an duplicate with https://github.com/tinytacoteam/zazu/issues/194, and now it's fixed by https://github.com/tinytacoteam/zazu-file-finder/pull/27. Could you give it another try?

**Comment by jan-schulz-k24** [comment]
@twang2218 Yep. it's fixed... But wow is it slow :-/ -> https://github.com/tinytacoteam/zazu-file-finder/issues/22
